"""
Transient ID generator — a fresh instance on every injection.

Demonstrates `@injectable(scope="transient")`: each call site that asks
for an IdGenerator gets a NEW instance. This is the right scope for any
stateful helper that should NOT share state across uses.

Use cases:
- Per-batch sequence generators
- Builder objects (BulkRequestBuilder, EmailComposer)
- Anything that needs a clean slate per injection point
"""

import uuid

from tachyon_api import injectable


@injectable(scope="transient")
class IdGenerator:
    """Fresh sequence/UUID generator for each injection point."""

    def __init__(self) -> None:
        self._sequence = 0

    def next_id(self) -> str:
        """Return a sequenced identifier: `<scope-prefix>-<n>`."""
        self._sequence += 1
        return f"id-{self._sequence:04d}"

    def next_uuid(self) -> str:
        """Return a fresh UUID4 string."""
        return str(uuid.uuid4())

    @property
    def count(self) -> int:
        """Number of IDs generated by this instance."""
        return self._sequence
